#!/usr/bin/env bash
# Regenerate data.js from your GitHub repos.
# Usage: ./build.sh [github-user]   (defaults to ScottYelich)
# Requires: gh (authenticated), python3
set -euo pipefail
USER="${1:-ScottYelich}"
cd "$(dirname "$0")"

echo "Fetching repos for $USER ..."
gh repo list "$USER" --limit 500 \
  --json name,description,visibility,url,homepageUrl,primaryLanguage,repositoryTopics,pushedAt,isArchived,isFork \
  > /tmp/portfolio_repos.json

GEN_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

python3 - "$GEN_DATE" <<'PY'
import json, sys, re

gen_date = sys.argv[1]
repos = json.load(open("/tmp/portfolio_repos.json"))

# Keyword -> category tag. Edit freely; first match(es) all apply.
CATEGORIES = {
    "trading":  r"trad|market|stock|candlestick|algo|sdts",
    "ai":       r"\bai\b|llm|agent|agentic|mlx|mind|memory|chat|alexa|shell|sasha|saixha|murphy|laniakea|yobro",
    "google":   r"google|gmail|workspace|\bgws\b",
    "devtools": r"build|orchestrat|\bdag\b|ybs|router|proxy|smith",
}

def tags_for(r):
    tags = []
    lang = (r.get("primaryLanguage") or {}).get("name")
    blob = f"{r['name']} {r.get('description') or ''}".lower()
    for cat, pat in CATEGORIES.items():
        if re.search(pat, blob):
            tags.append(cat)
    # topics from GitHub, if any
    rt = r.get("repositoryTopics") or []
    for t in rt:
        n = (t or {}).get("name")
        if n: tags.append(n)
    if lang: tags.append(lang)
    if r.get("isArchived"): tags.append("archived")
    if r.get("isFork"): tags.append("fork")
    # de-dupe, preserve order
    seen, out = set(), []
    for t in tags:
        k = t.lower()
        if k not in seen:
            seen.add(k); out.append(t)
    return out

out = []
for r in sorted(repos, key=lambda x: x.get("pushedAt") or "", reverse=True):
    out.append({
        "name": r["name"],
        "description": r.get("description") or "",
        "visibility": (r.get("visibility") or "").lower(),  # public|private
        "url": r["url"],
        "homepage": r.get("homepageUrl") or "",
        "language": (r.get("primaryLanguage") or {}).get("name") or "",
        "updated": (r.get("pushedAt") or "")[:10],
        "tags": tags_for(r),
    })

with open("data.js", "w") as f:
    f.write("// AUTO-GENERATED by build.sh — edit by hand if you want, but re-running build.sh overwrites this.\n")
    f.write(f'window.PORTFOLIO_GENERATED = "{gen_date}";\n')
    f.write("window.REPOS = " + json.dumps(out, indent=2, ensure_ascii=False) + ";\n")

pub = sum(1 for r in out if r["visibility"] == "public")
print(f"Wrote data.js: {len(out)} repos ({pub} public, {len(out)-pub} private)")
PY
