// AUTO-GENERATED by build.sh — edit by hand if you want, but re-running build.sh overwrites this.
window.PORTFOLIO_GENERATED = "2026-06-05T03:40:49Z";
window.REPOS = [
  {
    "name": "sdts",
    "description": "Scott & Daniel - Trading System",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/sdts",
    "homepage": "",
    "language": "Python",
    "updated": "2026-06-04",
    "tags": [
      "trading",
      "Python"
    ]
  },
  {
    "name": "yx",
    "description": "yx packet",
    "visibility": "public",
    "url": "https://github.com/ScottYelich/yx",
    "homepage": "",
    "language": "Python",
    "updated": "2026-04-27",
    "tags": [
      "Python"
    ]
  },
  {
    "name": "yobro",
    "description": "Alexa clone",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/yobro",
    "homepage": "",
    "language": "Python",
    "updated": "2026-04-13",
    "tags": [
      "ai",
      "Python"
    ]
  },
  {
    "name": "gws",
    "description": "Google workspace",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/gws",
    "homepage": "",
    "language": "Python",
    "updated": "2026-04-13",
    "tags": [
      "google",
      "Python"
    ]
  },
  {
    "name": "laniakea",
    "description": "LAN AI ... ",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/laniakea",
    "homepage": "",
    "language": "Python",
    "updated": "2026-04-13",
    "tags": [
      "ai",
      "Python"
    ]
  },
  {
    "name": "dagsmith",
    "description": "DAG smithy ... orchestrator, builds stuff.",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/dagsmith",
    "homepage": "",
    "language": "Swift",
    "updated": "2026-04-13",
    "tags": [
      "devtools",
      "Swift"
    ]
  },
  {
    "name": "ybs",
    "description": "Yelich Build System",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/ybs",
    "homepage": "",
    "language": "Shell",
    "updated": "2026-04-13",
    "tags": [
      "devtools",
      "Shell"
    ]
  },
  {
    "name": "saixha",
    "description": "Sasha:  AI Shell",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/saixha",
    "homepage": "",
    "language": "Swift",
    "updated": "2026-04-13",
    "tags": [
      "ai",
      "Swift"
    ]
  },
  {
    "name": "murphy",
    "description": "murphy chat w/ llm + tooling, etc.",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/murphy",
    "homepage": "",
    "language": "Swift",
    "updated": "2026-04-13",
    "tags": [
      "ai",
      "Swift"
    ]
  },
  {
    "name": "agent",
    "description": "General AI agent/worker continuous loop, etc.",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/agent",
    "homepage": "",
    "language": "Swift",
    "updated": "2026-04-13",
    "tags": [
      "ai",
      "Swift"
    ]
  },
  {
    "name": "mlx-router",
    "description": "MLX Router (proxy)",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/mlx-router",
    "homepage": "",
    "language": "Python",
    "updated": "2026-04-13",
    "tags": [
      "ai",
      "devtools",
      "Python"
    ]
  },
  {
    "name": "mind",
    "description": "mind - agentic processing stuffs",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/mind",
    "homepage": "",
    "language": "",
    "updated": "2026-04-12",
    "tags": [
      "ai"
    ]
  },
  {
    "name": "memory",
    "description": "Memories (for agentic systems work/use)",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/memory",
    "homepage": "",
    "language": "",
    "updated": "2026-04-12",
    "tags": [
      "ai"
    ]
  },
  {
    "name": "gmail-utility",
    "description": "General gmail utility: create, read, update, delete -- plus search, etc.  May then be called as agent /skill, etc.",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/gmail-utility",
    "homepage": "",
    "language": "Python",
    "updated": "2026-02-22",
    "tags": [
      "ai",
      "google",
      "Python"
    ]
  },
  {
    "name": "playground",
    "description": "playground",
    "visibility": "private",
    "url": "https://github.com/ScottYelich/playground",
    "homepage": "",
    "language": "",
    "updated": "2014-11-11",
    "tags": []
  }
];
